export const homeObjOne = {
    id:'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topline: 'About Us',
    headline: 'Vision :  To make mental health treatment accessible for one and all!',
    description: 'Stress has become a part of our lives in one way or another. As the world is becoming a lonelier place, we want to deal with it all by ourselves. This has led to a lot of mental health issues. Good Lives aims at helping you find the right guidance about keeping your mental health upright.',
    buttonLabel: 'Go to Blog',
    imgStart: false,
    img: require('../../Images/svg-1.svg').default,
    alt: 'Therapy',
    dark: true,
    where:'/blogs',
    primary: true,
    darkText: true
};
export const homeObjTwo = {
    id:'services',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topline: 'Our Services',
    headline: 'Therapies we offer',
    description: 'The aim of this therapy session is to help identify emotions and feelings that can often go unnoticed if not deliberately attended to. Therapies is used to create a safe environment for unnoticed emotions and feelings to come to surface via projective techniques. ',
    buttonLabel: 'Know More',
    imgStart: true,
    img: require('../../Images/tot.png').default,
    alt: 'Therapy',
    dark: true,
    where:'/servicesmore',
    primary: true,
    darkText: true
};
export const homeObjThree = {
    id:'experts',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topline: 'Our Experts',
    headline: 'Best suited therapist to cater to your requirements',
    description: 'Psychiatrist, psychologist, psychoanalyst, psychopharmacologist, psychotherapist and counsellor – Thinking about seeing a therapist but confused about all the different titles? Click below to understand the various professions within the mental health industry.',
    buttonLabel: 'Therapists',
    imgStart: false,
    img: require('../../Images/svg-13.svg').default,
    alt: 'Therapy',
    dark: true,
    where:'/types',
    primary: true,
    darkText: true
};
export const homeObjFour = {
    id:'team',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topline: 'Our Team',
    headline: 'Great Minds at work',
    description: 'Having seen people from all walks of life struggle with mental health problems, IIT Kharagpur alumni have taken a step towards making mental health services accessible. GoodLives aims to help people live a happier and healthier life. Fighting the stigma against seeking therapy and creating awareness are their prime objective.',
    buttonLabel: 'Testimonials',
    imgStart: true,
    img: require('../../Images/team.svg').default,
    alt: 'Therapy',
    dark: true,
    where:'/testimonials',
    primary: true,
    darkText: true
};